gubkina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import home_form_view


urlpatterns = [
    path('', home_form_view, name='main'),
]

main/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
import datetime
from django.core.validators import FileExtensionValidator


def year_choices():
    return [(r, r) for r in range(2000, datetime.date.today().year + 5)]


class MainInfoModel(models.Model):
    class GenderChoices(models.TextChoices):
        MALE = 'Male', 'Мужской'
        FEMALE = 'Female', 'Женский'

    class GraduationPlaceChoices(models.TextChoices):
        SCHOOL = "School", "Школа"
        COLLEGE = "College", "Колледж"
        LYCEUM = "Lyceum", "Лицей"
        UNIVER = "Univer", "ВУЗ"

    class MajorChoices(models.TextChoices):
        TECHNIC = 'Technic', 'Техническое направление'
        ECONOMIC = 'Economic', 'Экономическое направление'

    class MainTechnicMinorChoices(models.TextChoices):
        NONE = "None", "Выберите (приоритетный) профиль подготовки"
        GI = "GI", "Геофизические методы исследования скважин (ГИ) (специалитет)"
        GC = "GC", "Цифровой геоинжиниринг (ГЦ) (специалитет)"
        RB = "RB", "Бурение нефтяных и газовых скважин (РБ)"
        OS = "OS", "Эксплуатация и обслуживание объектов добычи нефти (РН)"
        DG = "DG", "Эксплуатация и обслуживание объектов добычи газа, газоконденсата и подземных хранилищ (РГ)"
        TS = "TS", "Сооружение и ремонт газонефтепроводов и газонефтехранилищ (ТС)"
        TP = "TP", "Эксплуатация и обслуживание объектов транспорта и хранения нефти, газа и продуктов переработки (ТП)"
        RT = "RT", "Технология бурения нефтяных и газовых скважин на суше и море (РТ) (специалитет)"
        RS = "RS", "Разработка и эксплуатация нефтяных и газовых месторождений (РС) (специалитет)"

    class SecondaryTechnicMinorChoices(models.TextChoices):
        NONE = "None", "Выберите дополнительный профиль подготовки"
        GI = "GI", "Геофизические методы исследования скважин (ГИ) (специалитет)"
        GC = "GC", "Цифровой геоинжиниринг (ГЦ) (специалитет)"
        RB = "RB", "Бурение нефтяных и газовых скважин (РБ)"
        OS = "OS", "Эксплуатация и обслуживание объектов добычи нефти (РН)"
        DG = "DG", "Эксплуатация и обслуживание объектов добычи газа, газоконденсата и подземных хранилищ (РГ)"
        TS = "TS", "Сооружение и ремонт газонефтепроводов и газонефтехранилищ (ТС)"
        TP = "TP", "Эксплуатация и обслуживание объектов транспорта и хранения нефти, газа и продуктов переработки (ТП)"
        RT = "RT", "Технология бурения нефтяных и газовых скважин на суше и море (РТ) (специалитет)"
        RS = "RS", "Разработка и эксплуатация нефтяных и газовых месторождений (РС) (специалитет)"

    class MainEconomicMinorChoices(models.TextChoices):
        NONE = "None" , "Выберите (приоритетный) профиль подготовки"
        EE = "EE", "Экономика и проекты устойчивого развития энергетики (ЭЭ)"
        EM = "EM", "Управление бизнесом в энергетике (ЭМ)"

    class SecondaryEconomicMinorChoices(models.TextChoices):
        NONE = "None" , "Выберите второй дополнительный профиль подготовки"
        EE = "EE", "Экономика и проекты устойчивого развития энергетики (ЭЭ)"
        EM = "EM", "Управление бизнесом в энергетике (ЭМ)"
    
    class NeedDormitoryChoices(models.TextChoices):
        YES = "Yes", "Да"
        NO = "No", "Нет"

    class IsOlympWinnerChoices(models.TextChoices):
        YES = "Yes", "Да"
        NO = "No", "Нет"
        
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=10, choices=GenderChoices.choices)
    birth_date = models.DateField()
    nationality = models.CharField(max_length=50)
    birth_place = models.CharField(max_length=200)
    living_place = models.CharField(max_length=200)
    citizenship = models.CharField(max_length=200)
    identity_document_name = models.CharField(max_length=100)
    identity_document_ser = models.CharField(max_length=10)
    identity_document_id = models.CharField(max_length=100)
    identity_document_issued_info = models.CharField(max_length=400)
    home_phone_number = PhoneNumberField(null=True, blank=True)
    own_phone_number = PhoneNumberField()
    email = models.EmailField()
    # graduation fields
    graduation_place = models.CharField(
        max_length=20,
        choices=GraduationPlaceChoices.choices, 
        default=GraduationPlaceChoices.SCHOOL
    )
    graduation_certificate_ser = models.CharField(max_length=50)
    graduation_year = models.IntegerField(choices=year_choices())
    copy_passport = models.FileField(
        upload_to='files/passports',
        validators=[FileExtensionValidator(
            allowed_extensions=["pdf", "jpg", "jpeg", "png"]
        )])
    copy_passport_habitance = models.FileField(
        upload_to='files/passports',
        validators=[FileExtensionValidator(
            allowed_extensions=["pdf", "jpg", "jpeg", "png"]
        )],
        null=True,
        blank=True)
    copy_graduation_certificate = models.FileField(
        upload_to='files/gr_certificates',
        validators=[FileExtensionValidator(
            allowed_extensions=["pdf", "jpg", "jpeg", "png"]
        )])
    image_three_to_four = models.FileField(
        upload_to='files/three_to_four',
        validators=[FileExtensionValidator(
            allowed_extensions=["pdf", "jpg", "jpeg", "png"]
        )])
    # majoring fields
    major_choice = models.CharField(
        max_length=200,
        choices=MajorChoices.choices,
        default=None
    )
    technic_major_choice_first = models.CharField(
        max_length=200,
        choices=MainTechnicMinorChoices.choices,
        default=MainTechnicMinorChoices.NONE,
    )
    technic_major_choice_second = models.CharField(
        max_length=200,
        choices=SecondaryTechnicMinorChoices.choices,
        default=SecondaryTechnicMinorChoices.NONE,
    )
    technic_major_choice_third = models.CharField(
        max_length=200,
        choices=SecondaryTechnicMinorChoices.choices,
        default=SecondaryTechnicMinorChoices.NONE,
    )
    economic_major_choice_first = models.CharField(
        max_length=200,
        choices=MainEconomicMinorChoices.choices,
        default=MainEconomicMinorChoices.choices,
    )

    economic_major_choice_second = models.CharField(
        max_length=200,
        choices=SecondaryEconomicMinorChoices.choices,
        default=SecondaryEconomicMinorChoices.choices,
    )

    need_dormitory = models.CharField(
        max_length=5,
        choices=NeedDormitoryChoices.choices,
        default=NeedDormitoryChoices.NO
    )

    is_olymp_winner = models.CharField(
        max_length=5,
        choices=IsOlympWinnerChoices.choices,
        default=IsOlympWinnerChoices.NO
    )
    # confirming
    first_confirm = models.BooleanField()
    second_confirm = models.BooleanField()
    third_confirm = models.BooleanField()


email_addresses = {
    "GI": "gi@gubkin.uz",
    "GC": "gc@gubkin.uz",
    "RB": "rb@gubkin.uz",
    "OS": "rn@gubkin.uz",
    "DG": "rg@gubkin.uz",
    "TS": "ts@gubkin.uz",
    "TP": "tp@gubkin.uz",
    "RT": "rt@gubkin.uz",
    "RS": "rs@gubkin.uz",
    "EE": "ee@gubkin.uz",
    "EM": "em@gubkin.uz"
}

main/views.py
from django.shortcuts import render, HttpResponse
from .forms import MainInfoForm
from django.contrib import messages
from django.conf import settings
from PIL import Image
from PyPDF2 import PdfMerger
import time, jinja2, os
from pyhtml2pdf import converter
from .models import MainInfoModel, email_addresses
from django.core.mail import send_mail, EmailMessage
from gubkina.config import CONFIG




base_certificate_path = os.path.join("files", "gr_certificates")
base_passport_path = os.path.join("files", "passports")
base_three_to_four_path = os.path.join("files", "three_to_four")
# Create your views here


def convert_pdfs(instance):
    certificate_path = str(instance.copy_graduation_certificate)
    passport_path = str(instance.copy_passport)
    passport_habitance_path = str(instance.copy_passport_habitance)
    three_to_four_path = str(instance.image_three_to_four)

    merger = PdfMerger()

    if certificate_path.endswith(".pdf"):
        final_certificate_path = certificate_path
    else:
        image = Image.open(certificate_path)
        converted_file = image.convert('RGB')
        now = time.time()
        final_certificate_path = os.path.join(settings.BASE_DIR, "files",
                                              "samples", f"{now}.pdf")
        converted_file.save(final_certificate_path)
    merger.append(final_certificate_path)

    if passport_path.endswith(".pdf"):
        final_passport_path = passport_path
    else:
        image = Image.open(passport_path)
        converted_file = image.convert('RGB')
        now = time.time()
        final_passport_path = os.path.join(settings.BASE_DIR, "files",
                                           "samples", f"{now}.pdf")
        converted_file.save(final_passport_path)
    merger.append(final_passport_path)

    if passport_habitance_path.endswith(".pdf"):
        final_passport_habitance_path = passport_habitance_path
    else:
        image = Image.open(passport_habitance_path)
        converted_file = image.convert('RGB')
        now = time.time()
        final_passport_habitance_path = os.path.join(settings.BASE_DIR, "files",
                                           "samples", f"{now}.pdf")
        converted_file.save(final_passport_habitance_path)
    merger.append(final_passport_habitance_path)

    if three_to_four_path.endswith(".pdf"):
        final_three_to_four_path = three_to_four_path
    else:
        image = Image.open(three_to_four_path)
        converted_file = image.convert('RGB')
        now = time.time()
        final_three_to_four_path = os.path.join(settings.BASE_DIR, "files",
                                                "samples", f"{now}.pdf")
        converted_file.save(final_three_to_four_path)
    merger.append(final_three_to_four_path)
    
    os.remove(os.path.abspath(final_certificate_path))
    os.remove(os.path.abspath(final_passport_path))
    os.remove(os.path.abspath(final_passport_habitance_path))
    os.remove(os.path.abspath(final_three_to_four_path))

    merged_file_path = "files/merged_pages.pdf"
    merger.write(merged_file_path)

    return merged_file_path


def create_pdf_form(context, merged_file_path):
    template_loader = jinja2.FileSystemLoader("./")
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template("files/template.html")
    output_text = template.render(context)
    with open('files/new.html', 'w') as f:
        f.write(output_text)

    now = time.time()
    rendered_file_path = f'files/{now}.pdf'
    old_html_file_path = os.path.abspath('files/new.html')
    converter.convert(f'file:///{old_html_file_path}', rendered_file_path)
    # merging finally

    merger = PdfMerger()
    merger.append(rendered_file_path)
    merger.append(merged_file_path)
    now = time.time()
    final_merged_file_path = f"files/merged_files/{now}.pdf"
    merger.write(final_merged_file_path)

    # removing
    old_rendered_file_path = os.path.abspath(rendered_file_path)
    os.remove(old_rendered_file_path)
    old_merged_file_path = os.path.abspath(merged_file_path)
    os.remove(old_merged_file_path)
    os.remove(old_html_file_path)

    return final_merged_file_path


def get_final_major_choice_name(cleaned_data):
    final_major_choice_name = ''
    if cleaned_data['major_choice'] == MainInfoModel.MajorChoices.TECHNIC:
        final_major_choice_name += cleaned_data['technic_major_choice_first_name']
        if cleaned_data['technic_major_choice_second'] != MainInfoModel.MainTechnicMinorChoices.NONE:
            final_major_choice_name += ',  ' + cleaned_data['technic_major_choice_second_name']
        if cleaned_data['technic_major_choice_third'] != MainInfoModel.MainTechnicMinorChoices.NONE:
            final_major_choice_name += ',  ' + cleaned_data['technic_major_choice_third_name']       
    else:
        final_major_choice_name += cleaned_data['economic_major_choice_first_name']
        if cleaned_data['economic_major_choice_second'] != MainInfoModel.MainTechnicMinorChoices.NONE:
            final_major_choice_name += ',  ' + cleaned_data['economic_major_choice_second_name']
    return final_major_choice_name


def home_form_view(request):
    context = {}
    if request.method == "GET":
        form = MainInfoForm()
        context['form'] = form
    elif request.method == "POST":
        form = MainInfoForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            cleaned_data = form.cleaned_data
            cleaned_data['gender'] = instance.get_gender_display()
            cleaned_data['graduation_place'] = instance.get_graduation_place_display()
            cleaned_data['need_dormitory'] = instance.get_need_dormitory_display()
            cleaned_data['is_olymp_winner'] = instance.get_is_olymp_winner_display()
            if cleaned_data["major_choice"] == MainInfoModel.MajorChoices.TECHNIC:
                cleaned_data['technic_major_choice_first_name'] = instance.get_technic_major_choice_first_display()
                cleaned_data['technic_major_choice_second_name'] = instance.get_technic_major_choice_second_display()
                cleaned_data['technic_major_choice_third_name'] = instance.get_technic_major_choice_third_display()
                cleaned_data["economic_major_choice_first"] == MainInfoModel.MainEconomicMinorChoices.NONE
                cleaned_data["economic_major_choice_second"] == MainInfoModel.MainEconomicMinorChoices.NONE
            else:

                cleaned_data['economic_major_choice_first_name'] = instance.get_economic_major_choice_first_display()
                cleaned_data['economic_major_choice_second_name'] = instance.get_economic_major_choice_second_display()
                cleaned_data["technic_major_choice_first"] = MainInfoModel.MainTechnicMinorChoices.NONE
                cleaned_data["technic_major_choice_second"] = MainInfoModel.MainTechnicMinorChoices.NONE
                cleaned_data["technic_major_choice_third"] = MainInfoModel.MainTechnicMinorChoices.NONE
            cleaned_data['final_major_choice_name'] = get_final_major_choice_name(cleaned_data)
            # some pdf action is here
            instance = form.save()
            if cleaned_data['home_phone_number']:
                cleaned_data['home_phone_number'] = cleaned_data['home_phone_number'].as_e164
            cleaned_data['own_phone_number'] = cleaned_data['own_phone_number'].as_e164
            #emails
            receiver_email_addresses = []
            if cleaned_data["major_choice"] == MainInfoModel.MajorChoices.TECHNIC:  
                technic_major_choice_first_email = email_addresses[cleaned_data["technic_major_choice_first"]]
                receiver_email_addresses.append(technic_major_choice_first_email)
            else:  
                economic_major_choice_first_email = email_addresses[cleaned_data["economic_major_choice_first"]]
                receiver_email_addresses.append(economic_major_choice_first_email)
            initial_merged_file_path = convert_pdfs(instance=instance)
            final_merged_file_path = create_pdf_form(cleaned_data, initial_merged_file_path)

            email = EmailMessage(
                subject="Subject",
                body="",
                from_email=CONFIG.email_host_user,
                to=receiver_email_addresses,
            )
            email.attach_file(final_merged_file_path)
            email.send()
            context['form'] = MainInfoForm()
            messages.success(request, 'Ваше заявление отправлено и обрабатывается технической группой приемной комиссии. Ожидайте смс-уведомление с регистрационным номером в течении 24 часов.')
        else:
            errors_dict = form.errors.as_data()
            first_error_message = errors_dict[list(errors_dict.keys())[0]][0].messages[0]
            messages.warning(request, first_error_message)
        context['form'] = form

    return render(request, 'main/main.html', context=context)

main/templates/main/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'main/imgs/logo.png' %}" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.10/dist/sweetalert2.min.css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.10/dist/sweetalert2.all.min.js"></script>

    <title>Онлайн подача документов</title>
  </head>
  <body>
    <header id="main_header">
      <div class="container">
        <div class="wrapper_items">
          <img
            src="{% static 'main/imgs/logo2.png' %}"
            alt="Губкинский университет"
            class="nav_logo"
          />
          <div class="tel_call">
            <a href="tel:+998 71 200-01-56" class="call_center"
              >Колл центр: +998 71 200-01-56</a
            >
          </div>
        </div>
      </div>
    </header>
    <div>
      {% if messages %}
        {% for message in messages %}
            {% if message.tags == "warning" %}
                <script>
                    Swal.fire(
                      "Что-то пошло не так :(", "{{message}}", "warning"
                    )
                </script>
            {% else %}
                <script>
                    Swal.fire(
                          "Уважаемый абитуриент!", "{{message}}", "success"
                        )
                </script>
            {% endif %}
        {% endfor %}
      {% endif %}
    </div>
    <div class="container">
      <form action="{% url 'main' %}" method="post" enctype="multipart/form-data" invalidate>
        {% csrf_token %}
        <div class="sub_parent">
          <h1 class="sub_title">Онлайн подача документов</h1>
          <h3 class="info_text">Введите следующие данные:</h3>
        </div>
        <div class="form_wrapper">
          <div class="personal_data">
            <div class="input_box">
              <label for="surname">Фамилия:</label>
              {{ form.last_name }}
            </div>
            <div class="input_box">
              <label for="name">Имя:</label>
              {{ form.first_name }}
            </div>
            <div class="input_box">
              <label for="f-name">Отчество:</label>
              {{ form.middle_name }}
            </div>
            <div class="input_box">
              <div class="radio_name">
                <p class="rad_input">Пол:</p>
              </div>
              {{ form.gender }}
            </div>
            <div class="input_box">
              <label for="nat_doc">Дата рождения:</label>
              {{ form.birth_date }}
            </div>
            <div class="input_box">
              <label for="nat_doc">Национальность:</label>
              {{ form.nationality }}
            </div>
            <div class="input_box">
              <label for="nat_doc">Место рождения:</label>
              {{ form.birth_place }}
            </div>
            <div class="input_box">
              <label for="nat_doc">Место проживания:</label>
              {{ form.living_place }}
            </div>
            <div class="input_box">
              <label for="gmail">Нуждаюсь в общежитии:</label>
              {{ form.need_dormitory }}
            </div>
            <br />
            <div class="input_box">
              <label for="gmail">Победитель Республиканских олимпиад:</label>
              {{ form.is_olymp_winner }}
            </div>
          </div>
          <div class="second_part">
            <div class="input_box">
              <label for="nat_doc">Гражданство:</label>
              {{ form.citizenship }}
            </div>
            <div class="input_box">
              <label for="nat_doc">Документ удостоверяющий личность:</label>
              {{ form.identity_document_name }}
            </div>
            <div class="input_box">
              <div class="double_data">
                <label for="seria">Серия:</label>
                {{ form.identity_document_ser }}
              </div>
              <div class="double_data">
                <label for="num">№:</label>
                {{ form.identity_document_id }}
              </div>
            </div>
            <div class="input_box">
              <label for="pass">Когда и кем выдан:</label>
              {{ form.identity_document_issued_info }}
            </div>
            <div class="input_box">
              <label for="phone">Телефон (дом):</label>
              {{ form.home_phone_number }}
            </div>
            <div class="input_box">
              <label for="cell_phone">Телефон (сот):</label>
              {{ form.own_phone_number }}
            </div>
            <div class="input_box">
              <label for="gmail">Электронная почта:</label>
              {{ form.email }}
            </div>

          </div>
        </div>
        <div class="sub_parent">
          <h3 class="info_text">Загрузите следующие данные:</h3>
        </div>
        <div class="form_wrapper">
          <div class="personal_data">
            <div class="input_box">
              <p class="education">Оконченное образовательное учреждение:</p>
              {{ form.graduation_place }}
            </div>
            <div class="input_box">
              <label for="diploma">Серия и номер аттестата или диплома:</label>
              {{ form.graduation_certificate_ser }}
            </div>
            <div class="input_box">
              <label for="year_grad">Год окончания:</label>
              {{ form.graduation_year }}
            </div>
          </div>
          <div class="second_part">
            <div class="upload_file">
              <div class="file_design">
                <p class="instead_label">Загрузите копию паспорта:</p>
              </div>
              <div class="file_design">
                {{ form.copy_passport }}
              </div>
            </div>
            <div class="upload_file doc_box">
              <div class="file_design">
                <p class="instead_label">Загрузите нотариально заверенный перевод паспорта/ID карты или свидетельство о рождении:</p>
              </div>
              <div class="file_design">
                {{ form.copy_passport_habitance }}
              </div>
            </div>
            <div class="upload_file doc_box">
              <div class="file_design">
                <p class="instead_label">
                  Загрузите копию аттестата или диплома (справку ЕГЭ):
                </p>
              </div>
              <div class="file_design">
                {{ form.copy_graduation_certificate }}
              </div>
            </div>
            <div class="upload_file">
              <div class="file_design">
                <p class="instead_label">Загрузите фото 3x4:</p>
              </div>
              <div class="file_design">
                {{ form.image_three_to_four }}
              </div>
            </div>
          </div>
        </div>
        <div class="sub_parent">
          <h1 class="info_text">Выберите одно из двух направлений:</h1>
            {{ form.major_choice }}
        </div>
        <div class="two_programs form_wrapper">
          <div class="check_box tech_box">
            <div id="tech_faculties">
              <div class="select_faculty">
                {{ form.technic_major_choice_first }}
              </div>
              <div class="select_faculty">
                {{ form.technic_major_choice_second }}
              </div>
              <div class="select_faculty">
                {{ form.technic_major_choice_third }}
              </div>
            </div>
          </div>
          <div class="check_box eco_box">
            <div id="econ_faculties">
              <div class="select_faculty">
                {{ form.economic_major_choice_first }}
              </div>
              <div class="select_faculty">
                {{ form.economic_major_choice_second }}
              </div>
            </div>
          </div>
        </div>  
        <hr />
        <div class="statement">
          <div class="state_text">
            {{ form.first_confirm }}
            <label for="id_first_confirm" class="final_text">
              Подтверждаю, что информация, представленная мною в заявлении,
              является правильной, точной и полной; представленные мной
              документы являются подлинными.
            </label>
          </div>
          <div class="state_text">
            {{ form.second_confirm }}
            <label for="id_second_confirm" class="final_text">
              Согласен(-а) на передачу и обработку своих персональных данных в
              соответствии с Федеральным законом РФ от 27 июля 2006 года №
              152-ФЗ «О персональных данных».
            </label>
          </div>
          <div class="state_text">
            {{ form.third_confirm }}
            <label for="id_third_confirm" class="final_text">
              Предупреждён(а), что если в период моего обучения в филиале 
              РГУ нефти и газа (НИУ) имени И.М. Губкина в городе Ташкенте 
              в моих документах об образовании обнаружатся несанкционированные 
              изменения, то я буду отчислен(а) из университета. В этом случае 
              перечисленные за обучение денежные средства Филиалом не возвращаются.
            </label>
          </div>
        </div>
        <div class="last_text">
          <input type="submit" name="Отправить" class="btn_send" />
          <p class="approval">
            Нажимая кнопку «Отправить», Вы даёте согласие на обработку
            персональных данных и принимаете политику обработки персональных
            данных
          </p>
        </div>
      </form>
    </div>
  </body>
  <script src="{% static 'main/js/main.js' %}"></script>
</html>